export const ROOT_HELP_TEXT_SECONDARY = [
  '  uncheck                   Uncheck a checkbox by --element ref',
  '  focus                     Focus an element by --element ref',
  '  clear                     Clear an input by --element ref',
  '  drag                      Drag --from ref to --to ref',
  '  upload                    Upload --files to a file input by --element ref',
  '  dblclick                  Double-click element by --element ref',
  '  forward                   Navigate forward in browser history',
  '  scrollintoview            Scroll --element into view',
  '  get                       Get element property (--what: text, html, value, url, title)',
  '  is                        Check element state (--what: visible, enabled, checked)',
  '  inserttext                Insert text without key events',
  '  mouse move                Move mouse to --x --y coordinates',
  '  mouse down                Press mouse button',
  '  mouse up                  Release mouse button',
  '  mouse wheel               Scroll wheel --dy [--dx]',
  '  find                      Find element by locator (--locator role|text|label --value <v>)',
  '  set device                Emulate device (--name "iPhone 12")',
  '  set offline               Toggle offline mode (--state on|off)',
  '  set headers               Set HTTP headers (--headers \'{"key":"val"}\')',
  '  set credentials           Set HTTP auth (--user <u> --pass <p>)',
  '  set media                 Set color scheme (--color-scheme dark|light)',
  '  clipboard read            Read clipboard contents',
  '  clipboard write           Write --text to clipboard',
  '  dialog accept             Accept browser dialog (--text for prompt response)',
  '  dialog dismiss            Dismiss browser dialog',
  '  storage local get         Get localStorage value by --key',
  '  storage local set         Set localStorage --key --value',
  '  storage local clear       Clear localStorage',
  '  storage session get       Get sessionStorage value by --key',
  '  storage session set       Set sessionStorage --key --value',
  '  storage session clear     Clear sessionStorage',
  '  download                  Download file via --selector to --path',
  '  highlight                 Highlight --selector on page',
  '  exec                      Run any agent-browser command (--command "...")',
  '',
  'Common Commands:',
  '  kingu open [--json]',
  '  kingu serve [--port <port>] [--pairing-address <host>] [--mobile-pairing] [--no-pairing] [--project-root <path>] [--recipe-json] [--json]',
  '  kingu status [--json]',
  '  kingu diagnostics memory [--json]',
  '  kingu agent-context [--json]',
  '  kingu search <query> [--scope conversation|all] [--fresh] [--limit <n>] [--cursor <c>] [--agent <id>] [--path <p>] [--since <iso>] [--sort relevance|newest] [--debug] [--json]',
  '  kingu search --index-status [--json]',
  '  kingu account add [--agent claude|codex] [--json]',
  '  kingu account list [--json]',
  '  kingu host list [--json]',
  '  kingu environment add --name <name> --pairing-code <code> [--json]',
  '  kingu environment list [--json]',
  '  kingu environment show --environment <selector> [--json]',
  '  kingu environment rm --environment <selector> [--json]',
  '  kingu worktree list [--repo <selector>] [--limit <n>] [--json]',
  '  kingu worktree create --name <name> [--repo <selector>|--project <id> [--host <host-id>]|--project-host-setup <id>] [--agent <id>] [--prompt <text>] [--setup run|skip|inherit] [--base-branch <ref>] [--issue <number>] [--linear-issue <identifier-or-url>] [--comment <text>] [--parent-worktree <selector>] [--no-parent] [--run-hooks] [--activate] [--json]',
  '  kingu worktree show --worktree <selector> [--json]',
  '  kingu worktree current [--json]',
  '  kingu worktree set --worktree <selector> [--display-name <name>] [--issue <number|null>] [--linear-issue <identifier-or-url|null>] [--comment <text>] [--workspace-status <id>] [--parent-worktree <selector>|--no-parent] [--json]',
  '  kingu worktree rm --worktree <selector> [--force] [--run-hooks] [--allow-failed-archive-hook] [--json]',
  '  kingu worktree ps [--limit <n>] [--json]',
  '  kingu file open <path> [--worktree <selector>] [--json]',
  '  kingu file diff <path> [--staged] [--worktree <selector>] [--json]',
  '  kingu file open-changed [--mode edit|diff|both] [--worktree <selector>] [--json]',
  '  kingu terminal list [--worktree <selector>] [--limit <n>] [--include-visual-layouts] [--json]',
  '  kingu terminal show [--terminal <handle>] [--json]',
  '  kingu terminal read [--terminal <handle>] [--cursor <n>] [--limit <n>] [--json]',
  '  kingu terminal send [--terminal <handle>] [--text <text>] [--enter] [--interrupt] [--wait-submit <seconds>] [--retry-request <id>] [--json]',
  '  kingu terminal wait [--terminal <handle>] --for exit|tui-idle [--timeout-ms <ms>] [--json]',
  '  kingu terminal create [--worktree <selector>] [--title <name>] [--command <text>] [--shell <shell>] [--focus] [--json]',
  '  kingu terminal split [--terminal <handle>] [--direction horizontal|vertical] [--json]',
  '  kingu terminal switch [--terminal <handle>] [--json]',
  '  kingu terminal close ([--terminal <handle>] [--tab] | --worktree <selector> --all) [--json]',
  '  kingu project list [--json]',
  '  kingu project setups [--project <id>] [--host <host-id>] [--json]',
  '  kingu project setup-existing-folder --project <id> --host <host-id> --path <path> [--kind git|folder] [--display-name <name>] [--json]',
  '  kingu project setup-clone --project <id> --host <host-id> --url <clone-url> --destination <path> [--display-name <name>] [--json]',
  '  kingu project setup-create --project <id> --host <host-id> [--setup-id <id>] [--path <path>] [--kind git|folder] [--display-name <name>] [--worktree-base-path <path>] [--git-username <name>] [--state ready|not-set-up|setting-up|error|unsupported] [--method imported-existing-folder|cloned|provisioned] [--json]',
  '  kingu project setup-update --setup <setup-id> [--display-name <name>] [--path <path>] [--worktree-base-path <path>] [--git-username <name>] [--kind git|folder] [--state ready|not-set-up|setting-up|error|unsupported] [--method legacy-repo|imported-existing-folder|cloned|provisioned] [--json]',
  '  kingu project setup-delete --setup <setup-id> [--json]',
  '  kingu repo list [--json]',
  '  kingu repo add --path <path> [--json]',
  '  kingu repo show --repo <selector> [--json]',
  '  kingu repo set-base-ref --repo <selector> --ref <ref> [--json]',
  '  kingu repo search-refs --repo <selector> --query <text> [--limit <n>] [--json]',
  '',
  'Selectors:',
  '  --repo <selector>         Registered repo selector such as id:<id>, name:<name>, or path:<path>',
  '  --worktree <selector>     Worktree selector such as identity:<identity>, id:<repo-id>::<path>, name:<displayName>, branch:<branch>, issue:<number>, path:<path>, or active/current',
  '  --terminal <handle>       Runtime-issued terminal handle returned by `kingu terminal list --json`',
  '  --parent-worktree <selector> Parent worktree selector such as identity:<identity>, id:<repo-id>::<path>, branch:<branch>, issue:<number>, path:<path>, or active/current',
  '  --no-parent               Force no parent lineage for unrelated worktree creation/update',
  '',
  'Terminal Send Options:',
  '  --text <text>             Text to send to the terminal',
  '  --enter                   Append Enter after sending text',
  '  --interrupt               Send as an interrupt-style input when supported',
  '  --wait-submit <seconds>   Observe this accepted prompt without resending it',
  '  --retry-request <id>      Resume the same durable prompt request after an ambiguous transport failure',
  '',
  'Terminal List Options:',
  '  --include-visual-layouts  Include tab and pane topology in JSON output',
  '',
  'Wait Options:',
  '  --for exit                Wait until the target terminal exits',
  '  --timeout-ms <ms>         Maximum wait time before timing out',
  '',
  'Output Options:',
  '  --json                    Emit machine-readable JSON instead of human text',
  '  --pairing-code <code>      Connect to a remote Kingu runtime using an kingu://pair?... code',
  '  --environment <selector>   Connect using a saved environment id or name',
  '  --help                    Show this help message',
  '',
  'Behavior:',
  '  Most commands require a running Kingu runtime. If Kingu is not open yet, run `kingu open` first.',
  '  Remote runtime access can also be supplied with KINGU_PAIRING_CODE or KINGU_ENVIRONMENT.',
  '  Use selectors for discovery and handles for repeated live terminal operations.',
  '',
  'Agent Sessions And Worktrees:',
  '  `worktree create --agent` creates a new checkout with an agent.',
  '  To start a fresh agent in the current worktree, use:',
  '    kingu terminal create --worktree active --command "codex"',
  '',
  'Browser Workflow:',
  '  1. Create or navigate:  kingu tab create --url https://example.com',
  '                          kingu goto --url https://example.com',
  '  2. Inspect the page:    kingu snapshot',
  '     (Returns an accessibility tree with element refs like e1, e2, e3)',
  '     For concurrent workflows, prefer: kingu tab list --json',
  '     then reuse tabs[].browserPageId with --page <id> on later commands.',
  '  3. Interact:            kingu click --element e2',
  '                          kingu fill --element e5 --value "search query"',
  '                          kingu keypress --key Enter',
  '  4. Re-inspect:          kingu snapshot',
  '     (Element refs change after navigation — always re-snapshot before interacting)',
  '',
  'Browser Options:',
  '  --element <ref>           Element ref from snapshot (e.g. @e3)',
  '  --url <url>               URL to navigate to',
  '  --value <text>            Value to fill or select',
  '  --input <text>            Text to type at current focus (no element needed)',
  '  --expression <js>         JavaScript expression to evaluate',
  '  --key <key>               Key to press (Enter, Tab, Escape, Control+a, etc.)',
  '  --direction <dir>         Scroll direction: up or down',
  '  --amount <pixels>         Scroll distance in pixels (default: viewport height)',
  '  --index <n>               Tab index (from `tab list`)',
  '  --page <id>               Stable browser page id (preferred for concurrent workflows)',
  '  --profile <id>            Browser profile id',
  "  --show-profile            Include the tab's browser profile in text output",
  '  --format <png|jpeg>       Screenshot image format',
  '  --from <ref>              Drag source element ref',
  '  --to <ref>                Drag target element ref',
  '  --files <path,...>        Comma-separated file paths for upload',
  '  --timeout <ms>            Wait timeout in milliseconds',
  "  --worktree <selector>     Scope commands to a specific worktree's browser tabs",
  '',
  'Examples:',
  '  $ kingu open',
  '  $ kingu status --json',
  '  $ kingu diagnostics memory --json',
  '  $ kingu repo list',
  '  $ kingu worktree create --name agent-task --agent codex --prompt "hi"',
  '  $ kingu worktree create --repo name:kingu --name cli-test-1 --issue 273',
  '  $ kingu worktree create --repo name:kingu --name linear-task --linear-issue https://linear.app/stably/issue/STA-335/test-issue',
  '  $ kingu worktree create --name linear-task --linear-issue STA-335',
  '  $ kingu worktree show --worktree branch:Jinwoo-H/cli',
  '  $ kingu worktree current',
  '  $ kingu worktree set --worktree active --comment "waiting on review"',
  '  $ kingu worktree set --worktree active --linear-issue null',
  '  $ kingu worktree ps --limit 10',
  '  $ kingu file open-changed --mode diff',
  '  $ kingu file open src/App.tsx',
  '  $ kingu terminal create --worktree active --command "codex"',
  '  $ kingu terminal list --worktree path:/Users/me/kingu/workspaces/kingu/cli-test-1 --json',
  '  $ kingu terminal send --terminal term_123 --text "hi" --enter',
  '  $ kingu terminal wait --terminal term_123 --for exit --timeout-ms 60000 --json',
  '  $ kingu tab current --json',
  '  $ kingu tab show --page page_123 --json',
  '  $ kingu tab create --url https://example.com --profile work',
  '  $ kingu tab profile clone --page page_123 --profile work --json',
  '  $ kingu snapshot',
  '  $ kingu click --element e3',
  '  $ kingu fill --element e5 --value "hello"',
  '  $ kingu goto --url https://example.com/login',
  '  $ kingu keypress --key Enter',
  '  $ kingu eval --expression "document.title"',
  '  $ kingu tab list --json'
].join('\n')
